import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import React, { useState } from "react";
import { Eye, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { motion } from "framer-motion";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import BioPreview from "./BioPreview";
export default function TemplateCard({ template, index, onSelect }) {
    const [previewOpen, setPreviewOpen] = useState(false);
    return (_jsxs(_Fragment, { children: [_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { delay: index * 0.08, duration: 0.4 }, className: "group relative bg-white rounded-2xl border border-gray-200 overflow-hidden hover:shadow-xl hover:border-violet-200 transition-all duration-300", children: [_jsxs("div", { className: `aspect-[3/4] relative overflow-hidden ${template.bgClass}`, children: [_jsx("div", { className: "absolute inset-0 flex items-center justify-center p-6", children: _jsx("div", { className: "w-full max-w-[200px]", children: _jsx(BioPreview, { template: template, mini: true }) }) }), _jsxs("div", { className: "absolute inset-0 bg-black/0 group-hover:bg-black/30 transition-all duration-300 flex items-center justify-center gap-3 opacity-0 group-hover:opacity-100", children: [_jsxs(Button, { size: "sm", variant: "secondary", className: "rounded-full bg-white/90 backdrop-blur-sm text-gray-900 hover:bg-white shadow-lg", onClick: () => setPreviewOpen(true), children: [_jsx(Eye, { className: "h-4 w-4 mr-1.5" }), "Preview"] }), _jsxs(Button, { size: "sm", className: "rounded-full bg-violet-600 hover:bg-violet-700 text-white shadow-lg", onClick: () => onSelect(template), children: [_jsx(Check, { className: "h-4 w-4 mr-1.5" }), "Select"] })] })] }), _jsxs("div", { className: "p-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h3", { className: "font-semibold text-gray-900 text-sm", children: template.name }), template.premium ? (_jsx(Badge, { className: "bg-gradient-to-r from-amber-400 to-orange-400 text-white text-xs border-0", children: "Pro" })) : (_jsx(Badge, { variant: "secondary", className: "text-xs", children: "Free" }))] }), _jsx("p", { className: "text-xs text-gray-500 mt-1", children: template.description })] })] }), _jsx(Dialog, { open: previewOpen, onOpenChange: setPreviewOpen, children: _jsx(DialogContent, { className: "max-w-sm p-0 overflow-hidden rounded-3xl border-0", children: _jsx("div", { className: `p-6 min-h-[500px] ${template.bgClass}`, children: _jsx(BioPreview, { template: template }) }) }) })] }));
}
