export const templates = [
    {
        id: "minimal",
        name: "Minimal",
        description: "Clean and simple. Perfect for professionals.",
        bgClass: "bg-gradient-to-b from-gray-50 to-white",
        theme: "light",
        premium: false,
        styles: { buttonStyle: "solid", borderRadius: "rounded-xl" },
        price: 0,
    },
    {
        id: "aurora",
        name: "Aurora",
        description: "Stunning gradient background for creators.",
        bgClass: "bg-gradient-to-br from-violet-600 via-purple-500 to-pink-500",
        theme: "dark",
        premium: true,
        styles: { buttonStyle: "soft", borderRadius: "rounded-2xl" },
        price: 499,
    },
    {
        id: "midnight",
        name: "Midnight",
        description: "Sleek dark theme with elegant contrast.",
        bgClass: "bg-gradient-to-b from-gray-900 via-gray-800 to-gray-900",
        theme: "dark",
        premium: false,
        styles: { buttonStyle: "outline", borderRadius: "rounded-xl" },
        price: 0,
    },
    {
        id: "sunset",
        name: "Sunset",
        description: "Warm tones inspired by golden hour.",
        bgClass: "bg-gradient-to-br from-orange-400 via-rose-400 to-pink-500",
        theme: "dark",
        premium: true,
        styles: { buttonStyle: "gradient", borderRadius: "rounded-full" },
        price: 499,
    },
    {
        id: "ocean",
        name: "Ocean",
        description: "Calming blue tones for a serene feel.",
        bgClass: "bg-gradient-to-br from-cyan-500 via-blue-500 to-indigo-600",
        theme: "dark",
        premium: true,
        styles: { buttonStyle: "soft", borderRadius: "rounded-xl" },
        price: 699,
    },
    {
        id: "paper",
        name: "Paper",
        description: "Warm, elegant minimalism.",
        bgClass: "bg-gradient-to-b from-amber-50 to-orange-50",
        theme: "light",
        premium: false,
        styles: { buttonStyle: "outline", borderRadius: "rounded-2xl" },
        price: 0,
    },
];
export const plans = [
    {
        name: "Basic",
        price: "Free",
        period: null,
        description: "Perfect to get started with your first bio page.",
        cta: "Start for Free",
        popular: false,
        features: [
            "1 Bio Page",
            "5 Links",
            "Basic Templates",
            "Linkfolio Branding",
            "Basic Analytics",
        ],
    },
    {
        name: "Pro",
        price: "₹299",
        period: "month",
        description: "Everything you need to grow your audience.",
        cta: "Upgrade to Pro",
        popular: true,
        features: [
            "Unlimited Bio Pages",
            "Unlimited Links",
            "All Premium Templates",
            "Remove Branding",
            "Advanced Analytics",
            "Custom Domain",
            "Priority Support",
        ],
    },
    {
        name: "Lifetime",
        price: "₹2,999",
        period: null,
        description: "Pay once, own it forever. Best value.",
        cta: "Get Lifetime Access",
        popular: false,
        features: [
            "Everything in Pro",
            "Lifetime Updates",
            "Early Access Features",
            "VIP Support",
            "API Access",
        ],
    },
];
export const dummyBioPages = [
    {
        id: "1",
        name: "Main Profile",
        username: "sarahchen",
        template: "aurora",
        views: 1243,
        clicks: 387,
        createdAt: "2026-01-15",
    },
    {
        id: "2",
        name: "Photography Portfolio",
        username: "sarahphotos",
        template: "midnight",
        views: 856,
        clicks: 214,
        createdAt: "2026-01-28",
    },
    {
        id: "3",
        name: "Workshop Links",
        username: "sarahworkshop",
        template: "minimal",
        views: 432,
        clicks: 98,
        createdAt: "2026-02-03",
    },
];
